name: Release Print Files

on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip print files
        run: zip -r ASTRO-print-files-${{ inputs.tag || github.ref_name }}.zip print_files/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag || github.ref_name }}
          name: ASTRO ${{ inputs.tag || github.ref_name }}
          files: ASTRO-print-files-${{ inputs.tag || github.ref_name }}.zip
          generate_release_notes: true
